

export const mockData = [{
	"ID": 1,
	"InfoID": 87,
	"Info": {
		"ID": 87,
		"DefaultEmailID": 8,
		"DefaultPhoneID": 41,
		"InvoiceAddressID": 107,
		"Name": "Mikke Mus",
		"DefaultPhone": {
			"ID": 41,
			"BusinessRelationID": 0,
			"CountryCode": "+999",
			"Description": "Mobile",
			"Number": "999-999-999",
			"Type": "0",
		},
		"DefaultEmail": {
			"ID": 8,
			"BusinessRelationID": 0,
			"Deleted": false,
			"Description": null,
			"EmailAddress": "mikke@mus.com",
		},
		"InvoiceAddress": {
			"ID": 107,
			"AddressLine1": "Andebygaten 33b",
			"AddressLine2": "2 etg.",
			"AddressLine3": "",
			"BusinessRelationID": 0,
			"City": "Andeby",
			"Country": "DisneyWorld",
			"CountryCode": "DW",
			"PostalCode": "341234-A",
			"Region": null,
		}
	},
	"Comment": "First comment",
	},
	{
		"ID": 2,
		"InfoID": 88,
		"Info": {
			"ID": 88,
			"DefaultEmailID": 9,
			"DefaultPhoneID": 42,
			"InvoiceAddressID": 108,
			"Name": "Donald Duck",
			"DefaultPhone": {
				"ID": 42,
				"BusinessRelationID": 1,
				"CountryCode": "+999",
				"Description": "Mobile",
				"Number": "123-929-933",
				"Type": "0",
			},
			"DefaultEmail": {
				"ID": 9,
				"BusinessRelationID": 1,
				"Deleted": false,
				"Description": null,
				"EmailAddress": "donnald@duck.com",
			},
			"InvoiceAddress": {
				"ID": 107,
				"AddressLine1": "Andebygaten 33c",
				"AddressLine2": "5 etg.",
				"AddressLine3": "",
				"BusinessRelationID": 1,
				"City": "Andeby",
				"Country": "DisneyWorld",
				"CountryCode": "DW",
				"PostalCode": "341234-A",
				"Region": null,
			}
		},
		"Comment": "First comment",
	},
	{
		"ID": 3,
		"InfoID": 89,
		"Info": {
			"ID": 89,
			"DefaultEmailID": 10,
			"DefaultPhoneID": 43,
			"InvoiceAddressID": 109,
			"Name": "Langbein Hund",
			"DefaultPhone": {
				"ID": 43,
				"BusinessRelationID": 2,
				"CountryCode": "+999",
				"Description": "Mobile",
				"Number": "554-987-374",
				"Type": "0",
			},
			"DefaultEmail": {
				"ID": 10,
				"BusinessRelationID": 2,
				"Deleted": false,
				"Description": null,
				"EmailAddress": "langbein@hund.com",
			},
			"InvoiceAddress": {
				"ID": 109,
				"AddressLine1": "Andebygaten 33b",
				"AddressLine2": "3 etg.",
				"AddressLine3": "",
				"BusinessRelationID": 2,
				"City": "Andeby",
				"Country": "DisneyWorld",
				"CountryCode": "DW",
				"PostalCode": "341234-A",
				"Region": null,
			}
		},
		"Comment": "First comment",
		}
]